server:
  port: 8082

spring:
  application:
    name: algamoneyApi
  datasource:
    url: jdbc:mysql://localhost:3306/algamoneyApi
    username: algamoney
    password: algamoney
    driver-class-name: com.mysql.cj.jdbc.Driver

    flyway:
      locations:
        classpath: db.migration

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri=http://localhost:8082/oauth/check_token:
          client-id=angular:
          client-secret=@ngul@r0:

  jpa:
    show-sql: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true

    date-format: yyyy-MM-dd


org:
  springframework:
    security:
      oauth2:
        server:
          resource:
            introspection:
              OpaqueTokenIntrospector://localhost:8082/oauth/check_token